services:
  cloud-db:
    image: postgres:15
    container_name: cloud-db
    environment:
      POSTGRES_DB: cloud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  cloud-backend:
    build: ./netology-diplom-backend-java
    container_name: cloud-backend
    depends_on:
      cloud-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cloud-db:5432/cloud_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/app/storage
    command: >
      sh -c "
      mkdir -p /app/storage &&
      java -jar /app/app.jar"

volumes:
  postgres_data: